---
- name: Download {{ kafka_download_url }}/kafka/{{ kafka_version }}/kafka_{{ kafka_version_scala }}-{{ kafka_version }}.tgz...
  become: yes
  get_url:
    dest: "/tmp/kafka_{{ kafka_version_scala }}-{{ kafka_version }}.tgz"
    url: "{{ kafka_download_url }}/kafka/{{ kafka_version }}/\
      kafka_{{ kafka_version_scala }}-{{ kafka_version }}.tgz"
    mode: "0644"

- name: Create {{ kafka_zookeeper_dataDir }} and {{ kafka_home_dir }}...
  become: yes
  file:
    path: "{{ kafka_zookeeper_dataDir }}"
    state: directory
    mode: "0755"
  with_items:
  - "{{ kafka_zookeeper_dataDir }}"
  - "{{ kafka_home_dir }}"

- name: Unarchive...
  become: yes
  unarchive:
    remote_src: yes
    src: /tmp/kafka_{{ kafka_version_scala }}-{{ kafka_version }}.tgz
    dest: "{{ kafka_home_dir }}"
    extra_opts: [--strip-components=1]

- name: Add SystemD scripts
  become: yes
  template:
    src: "{{ item.src }}"
    dest: /etc/systemd/system/{{ item.dest }}
    mode: u+rw,g+rw,o+r 
  with_items:
  - { src: 'zookeeper.service.j2', dest: 'zookeeper.service' }
  - { src: 'kafka.service.j2',     dest: 'kafka.service' }
  - { src: 'kafka-api.service.j2', dest: 'kafka-api.service' }
  - { src: 'override.conf.j2',     dest: 'override.conf' }

- name: Ensure Zookeeper and Kafka are enabled for SystemD
  become: yes
  systemd:
    daemon_reload: yes
    name: "{{ item }}"
    enabled: yes
  with_items:
  - zookeeper
  - kafka

- name: Configuring Zookeeper config file - zookeeper.properties
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
  - { src: 'zookeeper.properties.j2', dest: "{{ kafka_home_dir }}/config/zookeeper.properties" }
  - { src: 'server.properties.j2', dest: "{{ kafka_home_dir }}/config/server.properties" }
  - { src: 'myid.j2', dest: "{{ kafka_zookeeper_dataDir }}/myid" }
  notify:
    - Restart zookeeper service
    - Restart kafka service