---
- name: Set hostname and add mappings /etc/hosts
  hosts: elastic
  tags: set_hostname
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
    - name: Add mappings /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          {% for node in groups['elastic'] -%}
           {{ hostvars[node]['ansible_default_ipv4']['address'] }} {{ node }}
          {% endfor %}
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

- name: Install elasticsearch
  hosts: elastic
  vars_files: secret.yaml
  tags: elasticsearch
  roles:
    - role: ../roles/elasticsearch-cluster