---
# Variable setup.
- name: Include OS-Specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define jenkins_repo_url
  set_fact:
    jenkins_repo_url: "{{ __jenkins_repo_url }}"
  when: jenkins_repo_url is not defined

- name: Define jenkins_repo_key_url
  set_fact:
    jenkins_repo_key_url: "{{ __jenkins_repo_key_url }}"
  when: jenkins_repo_key_url is not defined

- name: Define jenkins_pkg_url
  set_fact:
    jenkins_pkg_url: "{{ __jenkins_pkg_url }}"
  when: jenkins_pkg_url is not defined

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Configure Jenkins init settings.
- include_tasks: settings.yml

# Add jenkins user sudoers
- name: Jenkins can run any command with no password
  lineinfile: 
    dest: /etc/sudoers
    regexp: '^jenkins'
    state: present
    line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

# Make sure Jenkins starts, then configure Jenkins.
- name: Ensure Jenkins is started and runs on startup.
  service: name=jenkins state=started enabled=yes

#  - name: Remove Jenkins init groovy scripts after first startup.
#   file:
#     path: "{{ jenkins_home }}/init.groovy.d/{{ item }}"
#     state: absent
#   with_items:
#     - 00-basic-security.groovy
#     - 01-install-plugins.groovy
#     - 02-setup-credentials.groovy
#     - 03-settings-golang-plugin.groovy
#     - 04-create-pipeline.groovy

- name: Template config.yml and kafka-api.service 
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: u+rw,g+rw,o+r 
  with_items:
    - { src: 'config.yml.j2',     dest: '/tmp/config.yml' }
    - { src: 'kafka-api.service.j2', dest: '/etc/systemd/system/kafka-api.service' }