---
- name: Check if jenkins_init_file exists.
  stat:
    path: "{{ jenkins_init_file }}"
  register: jenkins_init_file_stat

- name: Ensure jenkins_init_file exists.
  file:
    path: "{{ jenkins_init_file }}"
    state: touch
  when: not jenkins_init_file_stat.stat.exists

- name: Modify variables in init file.
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    insertafter: '^{{ item.option }}='
    regexp: '^{{ item.option }}=\"\${{ item.option }} '
    line: '{{ item.option }}="{{ item.value }}"'
    state: present
  with_items: "{{ jenkins_init_changes }}"
  register: jenkins_init_prefix

- name: Ensure jenkins_home {{ jenkins_home }} exists.
  file:
    path: "{{ jenkins_home }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: u+rwx
    follow: true

- name: Set the Jenkins home directory.
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    regexp: '^JENKINS_HOME=.*'
    line: 'JENKINS_HOME={{ jenkins_home }}'
  register: jenkins_home_config

- name: Set HTTP port in Jenkins config.
  lineinfile:
    backrefs: true
    dest: "{{ jenkins_init_file }}"
    regexp: '^{{ jenkins_http_port_param }}='
    line: '{{ jenkins_http_port_param }}={{ jenkins_http_port }}'
  register: jenkins_http_config

- name: Create custom init scripts directory.
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775
  
- name: configure default users
  template:
    src: "{{ item.src }}"
    dest: "{{ jenkins_home }}/init.groovy.d/{{ item.dest }}"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775
  with_items:
  - { src: '00-basic-security.groovy.j2', dest: '00-basic-security.groovy' }
  - { src: '01-install-plugins.groovy.j2', dest: '01-install-plugins.groovy' }
  - { src: '02-setup-credentials.groovy.j2', dest: '02-setup-credentials.groovy' }
  - { src: '03-settings-golang-plugin.groovy.j2', dest: '03-settings-golang-plugin.groovy' }
  - { src: '04-create-pipeline.groovy.j2', dest: '04-create-pipeline.groovy' }

- name: restart Jenkins on http or user changes.
  service: name=jenkins state=restarted
