---
- name: Update Debian based system
  apt:
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_os_family == 'Debian'

- name: Update RedHat based system
  yum:
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Install OpenJDK
  include_tasks: openjdk.yml
  when: install_openjdk|bool == true

- name: Install Oracle Java
  include_tasks: openjdk.yml
  when: install_openjdk|bool == no